jdbc.driverLocation=D:/work/maven_work/repository/mysql/mysql-connector-java/5.1.43/mysql-connector-java-5.1.43.jar
jdbc.driverClass=com.mysql.jdbc.Driver
jdbc.connectionURL=jdbc:mysql://127.0.0.1:3306/crm2022
jdbc.userId=root
jdbc.password=1508516782